---
# tasks/acls.yml - Configure Proxmox Access Control Lists (ACLs)
# Purpose: Grant permissions to users/groups on specific paths/resources
#
# Uses community.proxmox.proxmox_access_acl module for idempotent ACL management

- name: Configure ACL permissions
  community.proxmox.proxmox_access_acl:
    path: "{{ item.path }}"
    type: "{{ item.type }}"
    ugid: "{{ item.ugid }}"
    roleid: "{{ item.roleid }}"
    state: "{{ item.state | default('present') }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    validate_certs: "{{ proxmox_validate_certs }}"
  loop: "{{ proxmox_acls }}"
  delegate_to: localhost
  become: false
  register: proxmox_access_acl_result
  no_log: "{{ proxmox_no_log }}"

- name: Display ACL configuration status
  ansible.builtin.debug:
    msg: >-
      ACL {{ item.item.type }}/{{ item.item.ugid }} on '{{ item.item.path }}'
      → '{{ item.item.roleid }}' {{ 'configured' if item.changed else 'already set' }}
  loop: "{{ proxmox_access_acl_result.results }}"
  when: proxmox_access_acl_result.results is defined
  loop_control:
    label: "{{ item.item.path }}"
