---
# tasks/secrets.yml - Retrieve Proxmox API credentials from Infisical
# Purpose: Fetch root/admin credentials needed for API operations

- name: Retrieve Proxmox username from Infisical
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/infisical-secret-lookup.yml"
  vars:
    secret_name: 'PROXMOX_USERNAME'
    secret_var_name: 'proxmox_api_user'
    fallback_env_var: 'PROXMOX_USERNAME'

- name: Retrieve Proxmox password from Infisical
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/infisical-secret-lookup.yml"
  vars:
    secret_name: 'PROXMOX_PASSWORD'
    secret_var_name: 'proxmox_api_password'
    fallback_env_var: 'PROXMOX_PASSWORD'

- name: Display secret retrieval status
  ansible.builtin.debug:
    msg: "Proxmox API credentials retrieved for {{ proxmox_api_user }}"
  when: proxmox_api_user is defined
