---
# Update APT package cache

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_update_result
  retries: 3
  delay: 5
  until: apt_update_result is success
