---
# Deploy CEPH managers

- name: Check existing managers
  ansible.builtin.shell: |
    set -o pipefail
    ceph mgr dump | grep "{{ inventory_hostname_short }}" || true
  args:
    executable: /bin/bash
  register: existing_managers
  changed_when: false
  failed_when: false

- name: Create CEPH manager
  ansible.builtin.command: pveceph mgr create
  register: mgr_create
  changed_when: "'successfully created' in mgr_create.stdout or mgr_create.rc == 0"
  failed_when:
    - mgr_create.rc != 0
    - "'already exists' not in mgr_create.stderr"
    - "'already running' not in mgr_create.stderr"

- name: Wait for manager to be active
  ansible.builtin.shell: |
    set -o pipefail
    ceph mgr services | grep "{{ inventory_hostname_short }}"
  args:
    executable: /bin/bash
  register: mgr_status
  until: mgr_status.rc == 0
  retries: 10
  delay: 5
  changed_when: false

- name: Display manager status
  ansible.builtin.debug:
    msg: "CEPH manager on {{ inventory_hostname }}: {{ 'Created' if mgr_create is changed else 'Already exists' }}"
