name: Use Sync Labels Workflow
on:
  schedule:
    - cron: '0 0 * * 1' # 00:00 on Monday
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  sync-labels:
    # yamllint disable-line rule:line-length
    uses: basher83/.github/.github/workflows/sync-labels.yml@91d659ec9b5212af8b130d0c29f8d985c5e3f459
